# Chapter 13: Introduction to Modeling Libraries in Python

In [1]:
import pandas as pd
import numpy as np


In [5]:
# !pip3 install patsy
# !pip3 install statsmodels # This install scipy as well
# !pip3 install sklearn

## 13.1 Interfacing Between pandas and Model Code

In [19]:
# numpy array main entry point into modeling code
# use pd. values to get array from df
df = pd.DataFrame(np.random.randn(3,3),
                 columns=list('xyz'))
print(df)
print()
print(df.values)
print()

# if df contains non-numeric column, then returns python object instead of array
# ^actually I think this is wrong in the book?
df2 = df.assign(cat = list('cat'))
print(df2)
print()
print(df2.values)

          x         y         z
0 -0.097825  0.330839 -0.772891
1 -0.185997 -1.929895  1.142972
2 -1.669465  1.858885 -0.101421

[[-0.09782549  0.33083946 -0.77289098]
 [-0.18599733 -1.92989505  1.14297172]
 [-1.66946456  1.85888538 -0.10142126]]

          x         y         z cat
0 -0.097825  0.330839 -0.772891   c
1 -0.185997 -1.929895  1.142972   a
2 -1.669465  1.858885 -0.101421   t

[[-0.0978254872127047 0.33083946270968806 -0.7728909753020009 'c']
 [-0.1859973259311163 -1.9298950482046968 1.1429717235788583 'a']
 [-1.6694645637580399 1.8588853786334036 -0.10142125672844508 't']]


x         y         z
0  0.510020  0.460474  0.932837
1 -0.386415  0.816194 -0.213773
2 -0.289658  0.059980 -0.953676